services:
  elasticsearch:
    build: .
    image: elasticsearch:nori
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node


# Elasticsearch 서비스 구성
#포트 9200 노출
#discovery.type=single-node: 단일 노드 모드
#xpack.security.enabled=false: 보안 기능 비활성화