spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev

logging:
  level:
    com:
      back: debug

server:
  port: 8080
# spring.output.ansi.enabled: ?? ?? ? ANSI ??? ?? ??? (ALWAYS)
# logging.level.com.back: com.back ???? ?? ??? debug? ??
# server.port: ?? ??? 8080?? ??
# spring.jackson.serialization.fail-on-empty-beans: ? ?? ??? ? ?? ?? ?? (false)
# spring.profiles.active: ?? ???? dev? ??