spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com:
      back: debug
server:
  port: 8080

#spring.output.ansi.enabled: ?? ?? ? ANSI ??? ?? ??? (ALWAYS)
#logging.level.com.back: com.back ???? ?? ??? debug? ??
#server.port: ?? ??? 8080?? ??
